# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-18 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimes_against_women',
            old_name='Victims_Between_10to14_Yrs',
            new_name='Victims_Between_10_14_Yrs',
        ),
    ]
