# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-18 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180518_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='crimes_against_women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_Name', models.CharField(max_length=140)),
                ('Year', models.IntegerField()),
                ('Subgroup', models.CharField(max_length=140)),
                ('Rape_Cases_Reported', models.IntegerField()),
                ('Victims_Above_50_Yrs', models.IntegerField()),
                ('Victims_Between_10to14_Yrs', models.IntegerField()),
                ('Victims_Between_14to18_Yrs', models.IntegerField()),
                ('Victims_Between_18to30_Yrs', models.IntegerField()),
                ('Victims_Between_30to50_Yrs', models.IntegerField()),
                ('Victims_of_Rape_Total', models.IntegerField()),
                ('Victims_Upto_10_Yrs', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pod',
        ),
    ]
