# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-21 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180521_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='murder',
            old_name='Victims_Between_10to14_Yrs',
            new_name='Victims_Upto_10_15_Yrs',
        ),
        migrations.RenameField(
            model_name='murder',
            old_name='Victims_Between_14to18_Yrs',
            new_name='Victims_Upto_15_18_Yrs',
        ),
        migrations.RenameField(
            model_name='murder',
            old_name='Victims_Between_18to30_Yrs',
            new_name='Victims_Upto_18_30_Yrs',
        ),
        migrations.RenameField(
            model_name='murder',
            old_name='Victims_Between_30to50_Yrs',
            new_name='Victims_Upto_30_50_Yrs',
        ),
        migrations.RemoveField(
            model_name='murder',
            name='Victims_of_Rape_Total',
        ),
    ]
