# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-21 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180521_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Year',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='murder',
            name='Year',
            field=models.CharField(max_length=140),
        ),
    ]
